### PR TITLE
Restructure

### PR DESCRIPTION
**Pull request by masfiyan**
In this PR I have solve your code cleanup issue 

1- firstly to delete all extras Module which have not work in future
2- secondly I have deleted all commented Code
3- In some I have create comments for understand because other modules are not ready to fully perform there task because now we are still working on Fan network so that can our user will direct generate Models with it's requirement
4- Same in some modules I have done parametrized again same reason is that we are working on FAN so there are still changes

### CODE REVIEW

**Comment by shahzaibk23** [comment]
@masfiyan remove the src_dest Module from this PR. it is not finished YET, cannot merge it into main.

**Comment by shahzaibk23** [comment]
@syedowaisalishah , can you double check that all the FlexDPE and FAN related logic is not broken in this PR?

**Comment by syedowaisalishah** [comment]
@shahzaibk23 yes i double check all the module there is not any broken logic all are clear.

**Comment by masfiyan** [comment]
> @masfiyan remove the src_dest Module from this PR. it is not finished YET, cannot merge it into main.
@shahzaibk23 I have remove PathFinder related files -> SrcDest and muxVales

**Pull request merged**
